# Generated by Django 5.0.2 on 2024-02-24 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('capacity', models.IntegerField()),
                ('address', models.TextField(max_length=500)),
                ('is_available', models.BooleanField(default=True)),
                ('image', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('regi_members', models.TextField(default='', max_length=10000)),
                ('type', models.CharField(choices=[('entertainment', 'entertainment'), ('education', 'education')], max_length=50)),
                ('desc', models.TextField(max_length=1000)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('is_approved', models.BooleanField(default=False)),
                ('image', models.CharField(max_length=10000, null=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.committee')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('is_approved_all', models.BooleanField(default=False)),
                ('is_approved_pri', models.BooleanField(default=False)),
                ('is_approved_mentor', models.BooleanField(default=False)),
                ('is_approved_dean', models.BooleanField(default=False)),
                ('is_approved_hod', models.BooleanField(default=False)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.committee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.event')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.venue')),
            ],
        ),
    ]
