# Generated by Django 5.0.2 on 2024-02-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
